---
- hosts: localhost
  connection: local
  
  vars:
    kubeconfig: "{{ lookup('env','KUBECONFIG') }}"

  tasks:
    - block:
        - name: Test JS
          shell: echo {{ kubeconfig }}
          args:
            executable: /bin/bash